### ISSUE TITLE
Dynamic Block for optional `repo` and `build` not being applied

### ISSUE THREAD

**Issue by xPiSeaZx** [jfrog/terraform-provider-artifactory#745] opened 2023-06-05 03:30 UTC
**Describe the bug**
I am trying to use `Dynamic Blocks` to make the `repo` and/or `build` config options under `artifactory_permission_target` optional. This is working in `v6.29.0` and `v7.11.2` of the provider, but after upgrading to v8 the follow error is being displayed. Is this the correct approach for the optional config block:

```hcl
# main.tf (module)
resource "artifactory_permission_target" "this" {
  count = var.create_permissions ? 1 : 0

  name  = var.permission_name

  dynamic repo {
    for_each = var.add_repo_permissions ? [true] : []

    content {
      includes_pattern = var.repo_includes_pattern
      excludes_pattern = var.repo_excludes_pattern
      repositories     = var.repo_repositories

      actions {
        groups {
          name        = artifactory_group.this[0].name
          permissions = var.repo_permissions
        }
      }
    }
  }

  dynamic build {
    for_each = var.add_build_permissions ? [true] : []

    content {
      includes_pattern = var.build_includes_pattern
      excludes_pattern = var.build_excludes_pattern
      repositories     = var.build_repositories

      actions {
        groups {
          name        = artifactory_group.this[0].name
          permissions = var.build_permissions
        }
      }
    }
  }
}
```

Error message received:
```bash
Terraform v1.4.6
on linux_amd64
Initializing plugins and modules...
╷
│ Error: Invalid Attribute Value
│
│   with module.groups.artifactory_permission_target.this,
│   on ../../modules/security/groups/main.tf line 29, in resource "artifactory_permission_target" "this":
│   29: resource "artifactory_permission_target" "this" {
│
│ Attribute build.repositories must be set when build is defined.
╵
╷
│ Error: Invalid Attribute Value
│
│   with module.groups.artifactory_permission_target.this,
│   on ../../modules/security/groups/main.tf line 29, in resource "artifactory_permission_target" "this":
│   29: resource "artifactory_permission_target" "this" {
│
│ Attribute repo.repositories must be set when repo is defined.
╵
```

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
The `repo` and/or `build` config blocks should be ignored
```hcl
  # module.groups["terraform"].artifactory_permission_target.this[0] will be created
  + resource "artifactory_permission_target" "this" {
      + id   = (known after apply)
      + name = "terraform"

      + repo {
          + repositories = [
              + "ANY LOCAL",
            ]

          + actions {
              + groups {
                  + name        = "terraform"
                  + permissions = [
                      + "annotate",
                      + "delete",
                      + "manage",
                      + "managedXrayMeta",
                      + "read",
                      + "write",
                    ]
                }
            }
        }
    }
```

**Additional context**
terraform version: 1.4.6
terraform provider version: 8.0.0
artifactory version: 7.59.9

**Comment by alexhung** [comment] 2023-06-05 16:12
@xPiSeaZx Thanks for the report. This is caused by the resource being migrated to the new Terraform framework and the extra work we have to do to make it backward compatible. Looks like we have additional validation logic to add to take care of this use case.

**Comment by alexhung** [comment] 2023-06-15 20:48
@xPiSeaZx Using the latest v8.1.0 and the following configuration:

```terraform
# Required for Terraform 0.13 and up (https://www.terraform.io/upgrade-guides/0-13.html)
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "8.1.0"
    }
  }
}

provider "artifactory" {
  //  supply ARTIFACTORY_ACCESS_TOKEN / JFROG_ACCESS_TOKEN / ARTIFACTORY_API_KEY and ARTIFACTORY_URL / JFROG_URL as env vars
}

variable "create_permissions" {
  type = bool
  default = true
}

variable "permission_name" {
  type = string
  default = "test-permission"
}

variable "add_repo_permissions" {
  type = bool
  default = true
}

variable "repo_includes_pattern" {
  type = list(string)
  default = ["**"]
}

variable "repo_excludes_pattern" {
  type = list(string)
  default = []
}

variable "repo_repositories" {
  type = list(string)
  default = ["ANY LOCAL"]
}

variable "repo_permissions" {
  type = list(string)
  default = ["annotate", "delete", "manage", "managedXrayMeta", "read", "write"]
}

variable "add_build_permissions" {
  type = bool
  default = false
}

resource "artifactory_permission_target" "test-permission-target" {
  count = var.create_permissions ? 1 : 0

  name  = var.permission_name

  dynamic repo {
    for_each = var.add_repo_permissions ? [true] : []

    content {
      includes_pattern = var.repo_includes_pattern
      excludes_pattern = var.repo_excludes_pattern
      repositories     = var.repo_repositories

      actions {
        groups {
          name        = "test-group"
          permissions = var.repo_permissions
        }
      }
    }
  }

  dynamic build {
    for_each = var.add_build_permissions ? [true] : []

    content {
      includes_pattern = var.build_includes_pattern
      excludes_pattern = var.build_excludes_pattern
      repositories     = var.build_repositories

      actions {
        groups {
          name        = artifactory_group.this[0].name
          permissions = var.build_permissions
        }
      }
    }
  }
}
```

I get the following after executing `terraform plan` on a clean Artifactory instance:

```sh
alexh@alexh-mac terraform-provider-artifactory % terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # artifactory_permission_target.test-permission-target[0] will be created
  + resource "artifactory_permission_target" "test-permission-target" {
      + id   = (known after apply)
      + name = "test-permission"

      + repo {
          + excludes_pattern = []
          + includes_pattern = [
              + "**",
            ]
          + repositories     = [
              + "ANY LOCAL",
            ]

          + actions {
              + groups {
                  + name        = "test-group"
                  + permissions = [
                      + "annotate",
                      + "delete",
                      + "manage",
                      + "managedXrayMeta",
                      + "read",
                      + "write",
                    ]
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Let me know if you are seeing the same result. Will close this issue in a week's time if I don't hear from you.

**Comment by danielmkn** [comment] 2023-06-22 18:12
Closing due to inactivity.

**Closed by danielmkn** 2023-06-22 18:12 UTC
Labels: bug
