### ISSUE TITLE
external_depdencies_patterns not always applied

### ISSUE THREAD

**Issue by davidcorrigan714** [jfrog/terraform-provider-artifactory#673] opened 2023-03-01 21:06 UTC
**Describe the bug**
With the `artifactory_remote_docker_repository` resource it seems like `external_depdencies_patterns` isn't set on the server when `external_dependencies_enabled` is false. With both our provider & artifactory instance being updated this week that somehow got us in a state of a constant diff for `external_depdencies_patterns`. We have `external_dependencies_enabled` set to false in terraform, but the server still had the default value of [ '**' ] which this week just starting getting picked up as a diff for whatever reason. A terraform apply didn't resolve the diff by updating the server and we had to manually go through the UI on every repo to empty that list. Not hard to do but cost a few hours figuring out what was going on. The Terraform provider should either set `external_depdencies_patterns` indiscriminately or ignore the value of the field if `external_dependencies_enabled` is false.

Terraform version 1.3.6
Artifactory provider 7.0.0
Artifactory (cloud):  version 7.50.7, revision 75007900

**Requirements for and issue**
- [x] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

**Expected behavior**
 `external_depdencies_patterns` does not result in a constant diff irrespective of the value of `external_dependencies_enabled` either in Terraform or on the server.

**Comment by danielmkn** [comment] 2023-03-02 17:14
Hi @davidcorrigan714, can you explain how exactly it doesn't work? Is there an error message? If you try to create a new resource using HCL in example #2, it should throw an error:
```
"if `external_dependencies_enabled` is set to `false`, `external_dependencies_patterns` list can not be set"

**Comment by davidcorrigan714** [comment] 2023-03-02 17:21
It simply doesn't do the operation. It's not applied in Artfactory and it shows up in every subsequent plan as a diff.

**Comment by davidcorrigan714** [comment] 2023-03-02 17:22
Sorry, are you referring to my second example there? In that case I just commented out external_dependencies_patterns so you don't see the provider error. But it also doesn't empty the list, or even set external_dependencies_enabled to false in Artifatory

**Comment by danielmkn** [comment] 2023-03-02 17:22
I just tested both steps, and my results after applying the first and then the second HCL:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # artifactory_remote_docker_repository.my-remote-docker will be updated in-place
  ~ resource "artifactory_remote_docker_repository" "my-remote-docker" {
      ~ external_dependencies_enabled         = true -> false
      ~ external_dependencies_patterns        = [
          - "**",
        ]
        id                                    = "dcorriga-my-remote-docker"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }


Apply is successful, but in the repo properties I still see this: 
```
  "externalDependenciesEnabled": true,
  "externalDependenciesPatterns": ["**"],

The reason is when the attribute is not set, we don't send an empty array to Artifactory. As I understand, you want to remove the value from the attribute, if attribute is absent in the HCL?

**Comment by danielmkn** [comment] 2023-03-02 17:23
I see it now.

**Comment by danielmkn** [comment] 2023-03-02 17:27
Yeah, hold on, fixing it now.

**Comment by danielmkn** [comment] 2023-03-02 21:07
I fixed the problem with the boolean. But the problem with a list is not solvable in SDKv2. 
As you can see in the UI, `[**]` is a default value for `externalDependenciesPatterns`. Unfortunately, in SDKv2 it's impossible to set a default value for the list. Default works only for strings, ints, and booleans. 

When the repository is created initially, we use the `PUT` call, and can actually set that attribute to empty (by removing the attribute from the HCL). The problem arises when we try to update the repository by sending `POST` call, when there is no `externalDependenciesPatterns` set in the update call body (or it's an empty list `[]`), it gets set to `[**]` by Artifactory. So, when we get the repository info, we have a state drift. 
Usually, a situation like this is solvable by adding a default value for the attribute. We had a workaround there before, but that workaround broke import functionality.

Until we migrate to the plugin framework, the only workaround will be adding the attribute `external_dependencies_patterns` and assigning it a value of `[**]`.

**Comment by davidcorrigan714** [comment] 2023-03-02 21:50
Played with it a bit in Postman, wow that API is wonky and really just plain wrong. This should be a bug filed to Artifactory, it's not following any standard REST API conventions with that field. But if I create it with Terraform it's actually created ok-ish and has an empty list, it's not defaulting to [ "**" ] on initial creation like it does in the UI. Just then doesn't work if you want to set externalDependenciesEnabled to false.

From what I can tell with postman though, if the list is empty or missing it's just ignoring it which effectively means you can never set it to an empty list. Interestingly the API the UI uses works just fine - why there's 2 APIs is beyond me. Really should just have an API client generator that both public and internal clients all use, but I digress. It shouldn't be ignoring fields with a value, [] is a value that it's treating as null or a no-op which is flatly incorrect and leading to this bug. For example I could do a POST with [ "buffalo" ] then [] and it'll still be [ "buffalo" ], not reverting to [ "**" ]. All that was irrespective of the value I used for the externalDependenciesEnabled field.

So if `externalDependenciesPatterns` is set irrespective of `externalDependenciesEnabled` at least we could set it to [ "**" ] in the tf config manually, but since the provider errors if `externalDependenciesEnabled` is false we can't.

**Comment by danielmkn** [comment] 2023-03-02 21:55
100% agree with you on the API. I've changed the behavior, so you can set `externalDependenciesEnabled` to `false` and set `externalDependenciesPatterns` to `[**]` (or something else).

**Comment by danielmkn** [comment] 2023-03-02 21:56
Also removed `omitempty` from the `externalDependenciesPatterns`. Just need to test it thru and will release it today or tomorrow morning.

**Comment by danielmkn** [comment] 2023-03-03 00:05
@davidcorrigan714, please check v7.1.1

**Closed by danielmkn** 2023-03-03 00:05 UTC
Labels: bug

**Comment by davidcorrigan714** [comment] 2023-03-03 20:59
My example above is still broken. If external_dependencies_patterns isn't defined in the terraform file and it has a value in the UI there's always a diff because it can never set it back to '[]'. As long as the Artifactory API is broken there's no full solution in Terraform though. The root cause is that API needs to support an empty list as a value, so as long as the terraform provider accepts that as a valid value, and uses it as the default, it's going to be broken. Not sure what the import issue was you alluded to above, but if you set the default to [ "**" ] in terraform, then used a validator to make sure the input is never empty that should be the most consistent solution. Just means that if it's imported with an empty list it'll end up set to ['**'], but I don't think the empty list is ever a useful configuration.

**Comment by danielmkn** [comment] 2023-03-03 23:08
The problem is that in SDKv2 there is no default for the list. The workaround we had before, was adding [**] value to the attribute at the time of translating HCL into the API call body. That way you don't have a state drift. That approach was hacky and the import tests were failing. We had to remove it. 
I'll create a ticket for the Artifactory team to fix it. Unfortunately, this in not the only one API with this kind of behavior.

**Comment by davidcorrigan714** [comment] 2023-03-03 23:10
Oh I didn't realize Terraform doesn't support default values for those field types, good to know. Guess it is what it is for now.

**Comment by danielmkn** [comment] 2023-03-03 23:14
Sorry, I can't completely fix it. Thanks for the ticket and your patience! We will improve the UX when migrating to the plugin framework.
