### ISSUE TITLE
Module to create Global Environments using terraform

### ISSUE THREAD

**Issue by harishgoudb** [jfrog/terraform-provider-artifactory#773] opened 2023-07-28 18:11 UTC
Currently creating Global environments is missing in Terraform and customers want this feature to automate it via Terraform.

In order to create a Global Environment Via UI, we need to navigate to JFrog _Platform_UI | Admin |  Environments | Create New Environment.

https://jfrog.com/help/r/jfrog-rest-apis/environments

**Comment by alexhung** [comment] 2023-08-24 23:37
Closing this as it's duplicate of https://github.com/jfrog/terraform-provider-project/issues/78.

**Closed** 2023-09-08 17:59 UTC
Labels: enhancement
