### ISSUE TITLE
Download from provider registry is dead

### ISSUE THREAD

**Issue by roehrijn** [jfrog/terraform-provider-artifactory#247] opened 2021-12-14 14:47 UTC
Currently it isn't possible to download any version from `https://registry.terraform.io/providers/jfrog/artifactory`.
The API always returns an error, regardless which version or architecture is selected:

      curl 'https://registry.terraform.io/v1/providers/jfrog/artifactory/2.6.19/download/linux/amd64' 
      {"errors":["signing key 6B219DCCD7639232 not found for jfrog"]}

**Comment by alexhung** [comment] 2021-12-14 17:13
Duplicate of #240

**Closed by alexhung** 2021-12-14 17:13 UTC
Labels: bug, duplicate
