### ISSUE TITLE
Receiving "signing key 6B219DCCD7639232 not found for jfrog" on registry api endpt. for 2.6.22

### ISSUE THREAD

**Issue by mcilley** [jfrog/terraform-provider-artifactory#243] opened 2021-12-13 18:54 UTC
Error seen at this api end pt for v2.6.22
https://registry.terraform.io/v1/providers/jfrog/artifactory/2.6.22/download/linux/amd64

Not observed for v2.6.21
https://registry.terraform.io/v1/providers/jfrog/artifactory/2.6.21/download/linux/amd64

We leverage these endpts. To retrieve new releases for our private registry.

**Comment by alexhung** [comment] 2021-12-13 18:57
Duplicate of #240

**Closed** 2021-12-13 18:58 UTC
Labels: bug, duplicate

**Comment by Kamori** [comment] 2021-12-15 01:56
This appears to still be an issue. 2.6.22 and 2.2.7 were both signed by 6B219DCCD7639232 so they are not yet accessible.

```zsh
$ curl -s https://registry.terraform.io/v1/providers/jfrog/artifactory/2.2.7/download/linux/amd64 | jq  
{
  "errors": [
    "signing key 6B219DCCD7639232 not found for jfrog"
  ]
}
$ curl -s https://registry.terraform.io/v1/providers/jfrog/artifactory/2.6.22/download/linux/amd64 | jq  
{
  "errors": [
    "signing key 6B219DCCD7639232 not found for jfrog"
  ]
}```

**Comment by alexhung** [comment] 2021-12-15 06:43
@Kamori So far I haven't been able to discern the pattern on which versions are not available, and which aren't. 2.6.23 and 2.6.21 are both available. Similarly, 2.2.6 and 2.2.8 are available.

2.6.22 is available for darwin_amd64 but not linux_amd64.

**Comment by Kamori** [comment] 2021-12-15 22:36
In our situation, we pushed through to 2.6.23, so we are personally good. But it did introduce some pain :(
