### ISSUE TITLE
When destroying repositories, some repos don't get destroyed

### ISSUE THREAD

**Issue by Tobinatoe** [jfrog/terraform-provider-artifactory#612] opened 2022-12-23 09:31 UTC
**Describe the bug**
When attempting to destroy repositories, it doesn't destroy all of them. For some it only removes the project key.
This bug only seems to appear when you are admin of the project, but not the entire instance.
The not-deleted repos remain 'blacked out' outside of the project and can't be deleted anymore since we are only admins inside the project.

**Code Sippet**
```
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "6.22.2"
    }
  }
}

provider "artifactory" {
  url = "{your_artifactory_instance}"
  api_key = "{your_api_key}"
  check_license = false  
}

resource "artifactory_local_docker_v2_repository" "docker-release-local-0" {
  project_key               = "example"
  key                       = "example-docker-prod-local-0"
  block_pushing_schema1     = false
  tag_retention             = 1
  max_unique_tags           = 0
  project_environments      = ["PROD"]
}

resource "artifactory_local_docker_v2_repository" "docker-release-local-1" {
  project_key               = "example"
  key                       = "example-docker-prod-local-1"
  block_pushing_schema1     = false
  tag_retention             = 1
  max_unique_tags           = 0
  project_environments      = ["PROD"]
}

resource "artifactory_local_docker_v2_repository" "docker-release-local-2" {
  project_key               = "example"
  key                       = "example-docker-prod-local-2"
  block_pushing_schema1     = false
  tag_retention             = 1
  max_unique_tags           = 0
  project_environments      = ["PROD"]
}

resource "artifactory_local_docker_v2_repository" "docker-release-local-3" {
  project_key               = "example"
  key                       = "example-docker-prod-local-3"
  block_pushing_schema1     = false
  tag_retention             = 1
  max_unique_tags           = 0
  project_environments      = ["PROD"]
}
````

**Versions**
Terraform: v1.2.9
Artifactory: v7.0
Artifactory provider: v6.22.2

**Expected behavior**
I expected that when I run the command "terraform destroy" that all resources from that state get destroyed.

**Additional context**
1. The issue appears _almost_ every time we run the destroy command.
2. Reminder of the important condition that you are only admin of the project, not the instance.
3. I attached a screenshot of the error message that is thrown when attempting to destroy the repos.
![tempsnip](https://user-images.githubusercontent.com/45933703/209314860-5c56f22b-34b1-4254-8594-71a7f8e3b518.png)
This repos project key got removed, instead of destroying it and ended up outside of our permission scope.

**Comment by alexhung** [comment] 2023-01-03 17:23
@Tobinatoe We are back from our holiday time off. We'll investigate.

**Comment by Tobinatoe** [comment] 2023-01-16 08:54
Hi! Is there any update regarding this issue?

**Comment by alexhung** [comment] 2023-01-17 19:12
@Tobinatoe This is in our current sprint to be investigated.

**Comment by danielmkn** [comment] 2023-01-18 20:44
Most of the calls require the user to have admin access to the instance. 
As you've noticed, if you don't add `check_license = false` you get 403 when running `terraform apply`. 
In this particular case, I can't reproduce the described behavior. My steps: 

1. Create a new user with default roles (since there are no details provided in the ticket). So, nothing is selected in the `Roles` section. Only one group `Readers` is assigned. 
2. Create a new project `example` and assign created user as a Project admin. By default, all options in the `Project Admins Privileges` section are selected. Note: if `Manage Resources` is not selected, you will get 403 on the `terraform apply`, because this user can't create repositories.
3. I'm using the HCL example from this ticket and running `terraform apply`. All repositories are created and assigned to the project `example`. 
4. Run `terraform destroy` - all repositories are removed from the project and deleted from my instance, with no errors. 

The only scenario when I get 403 on destroy, is when I remove `Manage Resources` access from the project admin after running `terraform apply`, which is expected. 

This is my project settings screen: 
![image](https://user-images.githubusercontent.com/55418063/213289929-70ac95f7-caa4-499d-92d3-68431fa61321.png)

This is the user details pages: 
![image](https://user-images.githubusercontent.com/55418063/213290178-35fe7e7b-b2c0-4ea2-a5f5-d9a01d7a1f01.png)
![image](https://user-images.githubusercontent.com/55418063/213290338-b5a3a716-f9e9-4483-9d41-68500739e251.png)


@Tobinatoe, please make sure you have the correct permissions for the user. Please let me know if it doesn't work for you and provide more details about the user settings/permissions, I'll be happy to assist.

**Comment by danielmkn** [comment] 2023-01-20 01:25
@Tobinatoe, I'll close the issue tomorrow. Do you have any questions or comments?

**Closed** 2023-01-20 19:50 UTC
Labels: bug

**Comment by Tobinatoe** [comment] 2023-01-23 17:23
Hi, sorry for the delayed reply.

We are having a look at it and we will let you know in case the issue remains.

Thanks a lot for your help!

**Comment by danielmkn** [comment] 2023-01-23 17:26
Hi, no problem, feel free to reopen this ticket if you still have a problem.
