### ISSUE TITLE
Internal User is not associated with Group via `artifactory_group `

### ISSUE THREAD

**Issue by skyzyx** [jfrog/terraform-provider-artifactory#534] opened 2022-08-30 17:36 UTC
**Describe the bug**

We use Okta integration (SAML) for human users. We create _internal_ users for Service Accounts (e.g., automation, CI, "robots"). In this report, a _User_ (capitalized) represents a Service Account (auth is internal to Artifactory).

Truths:

* We add Users to Groups.
* We apply Permissions to Groups.
* We never apply Permissions directly to Users.

Context:

* A User can be assigned to zero or more Groups.
* There are several pre-existing Groups that a User MAY be added to (e.g., `readers`, `write-npm`).
* If a User needs custom Permissions (we grant write permissions to specific Docker namespaces without granting write access the entire Docker repo), we create a Group with the same name as the User, and add that User to that Group. We then apply Permissions to that Group.

With me so far?

Since a User always WILL exist, but a same-named Group MAY exist, it makes sense to define the association between the Group and the User in the `artifactory_group` resource. That is to say, only associate if they both exist.

That said, the Provider _also_ allows associating a User with a Group from the `artifactory_managed_user` resource. We don't use this because we don't want to risk adding a user to a `nil` Group which doesn't exist.

Here's the issue:

When adding a User to a Group by having the `artifactory_group` resource set its `users_names =` property to point to the `artifactory_managed_user` resource, no connection between the two is made.

**Requirements for and issue**

* [X] A description of the bug

    Above.

* [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue).

    **Module:**

    ```hcl
    # https://www.terraform.io/docs/configuration/terraform.html
    terraform {
        required_version = ">= 1.0, < 2.0"

        required_providers {
            # https://github.com/jfrog/terraform-provider-artifactory/releases/latest
            artifactory = {
                source  = "registry.terraform.io/jfrog/artifactory"
                version = ">= 6.5, < 7.0"
            }
            time = {
                source = "hashicorp/time"
            }
            random = {
                source = "hashicorp/random"
            }
        }
    }

    # https://registry.terraform.io/providers/jfrog/artifactory/latest/docs
    provider "artifactory" {
        url = "https://DOMAIN/artifactory"

        # Set $ARTIFACTORY_ACCESS_TOKEN to your Bearer Token.
    }

    variable "username" {
        description = "<p>The username of the service account. MUST begin with `svc_` and be formatted as snake_case. See [Create an Artifactory service account](#link) for details.</p>"
        type        = string

        validation {
            condition     = can(regex("^svc_([0-9a-z_]+)[0-9a-z]$", var.username))
            error_message = "Username MUST begin with 'svc_'; MUST be formatted as snake_case; MAY contain digits; MAY NOT end with an underscore."
        }
    }

    variable "distribution_list" {
        description = "<p>The distribution list email address (singular) for the team/app/service who manages this service account.</p><p><strong>DO NOT</strong> use an individual’s email address.</p><p>See [Create an Artifactory service account](#link) for details.</p>"
        type        = string

        validation {
            condition     = can(regex("@domain\\.com", var.distribution_list))
            error_message = "Legitimate distribution lists only end in @domain.com."
        }
    }

    variable "add_to_groups" {
        description = "<p>A list of _existing_, _standardized_ groups to add the user to upon creation. See `groups.txt` in the root of the repository for a list.</p>"
        type        = list(string)
        default     = []

        validation {
            condition     = !contains([for s in var.add_to_groups : lower(s)], ["admins"])
            error_message = "Adding users to the 'Admins' group is NOT PERMITTED."
        }
    }

    variable "create_group" {
        description = "<p>Whether or not to create a group with a matching name, and adding this user to this group. Required for assigning custom permissions.</p><p>A value of `true` will create the user with read permissions (added to 'reader' group), then also create a same-named group as a hook for attaching permissions. A value of `false` will create the user with read permissions (added to 'reader' group).</p>"
        type        = bool
        default     = false
    }

    variable "enable_docker_namespace" {
        description = "<p>The name of the Docker image namespace to use. A non-empty value will enable permissions for this user to read/write/annotate/delete under this Docker image namespace. Requires `create_group` to be `true`.</p>"
        type        = string
        default     = ""

        validation {
            condition     = can(regex("^[a-z]([0-9a-z_-]+)[0-9a-z]$", var.enable_docker_namespace)) || var.enable_docker_namespace == ""
            error_message = "Docker image namespace MUST be lowercase alphanumeric; MUST begin with a letter; MUST end with a alphanumeric character; MAY contain underscores (_) and/or hyphens (-)."
        }
    }

    # https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/managed_user
    resource "artifactory_managed_user" "service_user" {
        name   = var.username
        email  = var.distribution_list
        groups = concat(["readers"], var.add_to_groups)

        # Random password; MUST be set as of Artifactory Provider v4.0.0. But we don't
        # use it. As of Artifactory Provider v6.4.0, `artifactory_managed_user`
        # requires a password while `artifactory_unmanaged_user` does not.
        password = "${random_id.timestamp.keepers.ts}-${random_id.timestamp.hex}"

        admin                      = false
        profile_updatable          = false
        disable_ui_access          = true
        internal_password_disabled = true

        lifecycle {
            ignore_changes = [
                admin,
                disable_ui_access,
                internal_password_disabled,
                password,
                profile_updatable,
            ]
        }
    }

    # https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/group
    resource "artifactory_group" "service_group" {
        count = var.create_group ? 1 : 0

        name        = var.username
        description = "The '${var.username}' group is attached to the '${var.username}' user. Permissions should be applied to the group rather than the user."
        users_names = [artifactory_managed_user.service_user.name]

        auto_join        = false
        admin_privileges = false
        watch_manager    = false
        policy_manager   = false
        reports_manager  = false
    }

    # https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/permission_target
    resource "artifactory_permission_target" "service_docker_perms" {
        count = (var.create_group == true && var.enable_docker_namespace != "") ? 1 : 0

        name = var.username

        repo {
            includes_pattern = ["${var.enable_docker_namespace}/**"]
            repositories     = ["docker-local"]

            actions {
                groups {
                    name = var.username

                    # Manage the CONTENTS OF the Docker namespace, without touching the namespace itself.
                    permissions = [
                        "read",
                        "write",
                        "annotate",
                        "delete",
                    ]
                }
            }
        }
    }

    # https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/id
    resource "random_id" "timestamp" {
        byte_length = 32
        keepers = {
            ts = timestamp()
        }

        lifecycle {
            ignore_changes = [
                byte_length,
                keepers,
            ]
        }
    }
    ```

    **User code:**

    ```hcl
    module "service_user" {
        source = "git@github.company.com:terraform/artifactory-create-user.git?ref=main"

        # Pass in the variables
        add_to_groups           = []
        create_group            = true
        distribution_list       = "user@domain.com"
        enable_docker_namespace = "example"
        username                = "svc_example"
    }
    ```

* [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`

    EnterpriseX license 7.39.4 rev 73904900

* [X] Your version of terraform & provider

    ```plain
    Terraform v1.2.8
    on linux_amd64
    + provider registry.terraform.io/hashicorp/random v3.3.2
    + provider registry.terraform.io/hashicorp/time v0.8.0
    + provider registry.terraform.io/jfrog/artifactory v6.14.1
    ```

**Expected behavior**

The User should be added to the Group.

**Additional context**

I'm 75% certain that this worked in Provider 6.4.0.

**Comment by alexhung** [comment] 2022-08-30 20:12
@skyzyx Thanks for the detailed write up! I'll take a look.

**Comment by alexhung** [comment] 2022-08-30 20:24
@skyzyx Just a hunch after scanning the code quickly, have you tried adding `depends_on` to `artifactory_group.service_group`? e.g.

```hcl
resource "artifactory_group" "service_group" {
  ...
  depends_on = [artifactory_managed_user.service_user]
}
```

**Comment by skyzyx** [comment] 2022-08-31 04:09
I haven't, because normally the dependency is inferred by the explicit reference in users_names.

I'll give it a try in the morning.

**Comment by alexhung** [comment] 2022-08-31 16:34
@skyzyx I agree the dependency chain should be inferred from the reference but I've run into instances where TF doesn't recognize the dependency via reference. Only `depends_on` makes it work. 🤷🏼 Not entirely sure this is the case here but worth a try.

I don't have much time this week to look at this and I'll be traveling for work next week. So most likely I won't be able to take a deep look until the week after.

**Comment by skyzyx** [comment] 2022-09-06 19:34
Haven't had brain-space for the past week, but plan to follow-up on this issue this week.

**Comment by skyzyx** [comment] 2022-09-07 21:41
Tested. That's not working. Users are still being removed from groups.

Let me try checking variables to see if a custom group should be created, and then try adding from the user side.

Either way, I'm _pretty sure_ this is a legitimate bug.

**Comment by skyzyx** [comment] 2022-09-07 22:16
Reversing the directionality appears to have worked. From the User resource, including the new custom Group in the `groups = […]` property (attribute?) successfully sets the binding.

Conversely, from the Group resource, including the User in the `users_names = […]` property fails to bind the two resources together.

----

From the example above:

1. I removed `users_names = […]` from `resource "artifactory_group" "service_group" {}`.

1. I added a new local variable:

    ```hcl
    locals {
        add_group_to_groups = var.create_group ? [var.username] : []
    }
    ```

1. Then I updated `groups = […]` in `resource "artifactory_managed_user" "service_user" {}`.

    ```hcl
    resource "artifactory_managed_user" "service_user" {
        groups = concat(["readers"], var.add_to_groups, local.add_group_to_groups)
        depends_on = [artifactory_group.service_group]

        # ...
    }
    ```

**Comment by alexhung** [comment] 2022-09-08 06:31
@skyzyx Thanks, that's super helpful. We'll take it from here. /cc @danielmkn

**Comment by danielmkn** [comment] 2022-09-13 01:29
@skyzyx, thanks for the detailed information! 
However, I've tested the HCL provided and it works as expected for me. 
I use Artifactory 7.41.7 and TF provider 6.15.0
This is the HCL I used to test:
```
variable "username" {
  description = "<p>The username of the service account. MUST begin with `svc_` and be formatted as snake_case. See [Create an Artifactory service account](#link) for details.</p>"
  type        = string
  default     = "svc_example" # testing
}

variable "distribution_list" {
  description = "<p>The distribution list email address (singular) for the team/app/service who manages this service account.</p><p><strong>DO NOT</strong> use an individual’s email address.</p><p>See [Create an Artifactory service account](#link) for details.</p>"
  type        = string
  default     = "user@domain.com" # testing
}

variable "add_to_groups" {
  description = "<p>A list of _existing_, _standardized_ groups to add the user to upon creation. See `groups.txt` in the root of the repository for a list.</p>"
  type        = list(string)
  default     = []
}

variable "create_group" {
  description = "<p>Whether or not to create a group with a matching name, and adding this user to this group. Required for assigning custom permissions.</p><p>A value of `true` will create the user with read permissions (added to 'reader' group), then also create a same-named group as a hook for attaching permissions. A value of `false` will create the user with read permissions (added to 'reader' group).</p>"
  type        = bool
  default     = true # testing
}

variable "enable_docker_namespace" {
  description = "<p>The name of the Docker image namespace to use. A non-empty value will enable permissions for this user to read/write/annotate/delete under this Docker image namespace. Requires `create_group` to be `true`.</p>"
  type        = string
  default     = "example"
}

# https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/managed_user
resource "artifactory_managed_user" "service_user" {
  name   = var.username
  email  = var.distribution_list
  groups = concat(["readers"], var.add_to_groups)
  password = "${random_id.timestamp.keepers.ts}-${random_id.timestamp.hex}"

  admin                      = false
  profile_updatable          = false
  disable_ui_access          = true
  internal_password_disabled = true

  lifecycle {
    ignore_changes = [
      admin,
      disable_ui_access,
      internal_password_disabled,
      password,
      profile_updatable,
    ]
  }
}

# https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/group
resource "artifactory_group" "service_group" {
  count = var.create_group ? 1 : 0

  name        = var.username
  description = "The '${var.username}' group is attached to the '${var.username}' user. Permissions should be applied to the group rather than the user."
  users_names = [artifactory_managed_user.service_user.name]

  auto_join        = false
  admin_privileges = false
  watch_manager    = false
  policy_manager   = false
  reports_manager  = false
}

# https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/permission_target
resource "artifactory_permission_target" "service_docker_perms" {
  count = (var.create_group == true && var.enable_docker_namespace != "") ? 1 : 0

  name = var.username

  repo {
    includes_pattern = ["${var.enable_docker_namespace}/**"]
    repositories     = ["docker-local"]

    actions {
      groups {
        name = var.username

        # Manage the CONTENTS OF the Docker namespace, without touching the namespace itself.
        permissions = [
          "read",
          "write",
          "annotate",
          "delete",
        ]
      }
    }
  }
}

# https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/id
resource "random_id" "timestamp" {
  byte_length = 32
  keepers = {
    ts = timestamp()
  }

  lifecycle {
    ignore_changes = [
      byte_length,
      keepers,
    ]
  }
}
```

This is the result in my Artifactory instance:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/55418063/189786104-98ef3425-fc04-4075-98c5-90a7c78b199b.png">
You can see that the user was created and assigned to one pre-existing group 'readers' and one new group with the same name as the username. Custom permissions were also applied.

Also, you shouldn't worry to assign a user to a non-existing group, because the Provider will throw an error if you will do it: 
```
│ Error: 
│ 400 PUT https://your-instance.com/artifactory/api/security/users/svc_example
│ {
│   "errors" : [ {
│     "status" : 400,
│     "message" : "Unable to find group by name 'readers2'."
│   } ]
│ }
```

I found one inconsistency in the order of creation of resources on graph. When you run `terraform graph | dot -Tsvg > graph.svg` (install `graphviz` to have `dot` command), you can see that the group is located before the user, doesn't matter if you have an explicit or implicit dependency on the group resource. 
The order changes only if you add the dependency to the user object (which you want to avoid in your example). See the simplified example: 
<img width="705" alt="image" src="https://user-images.githubusercontent.com/55418063/189787286-2c18b458-4509-40ee-a368-609ad4a064b9.png">


We can have a Zoom session to figure out why it doesn't work for you if you want. Please, let me know.

**Comment by danielmkn** [comment] 2022-09-21 00:46
Since there is no activity on the ticket for a while and we can't reproduce the issue, I'm closing it. @skyzyx feel free to reopen it and ping me if you still experience the issue.

**Closed by danielmkn** 2022-09-21 00:46 UTC
Labels: bug, question

**Comment by skyzyx** [comment] 2022-09-21 20:47
While I am still experiencing this issue on my current version of Artifactory, we will need to schedule an upgrade to the latest version before I could validate either way. In the interim, I have a workaround that gives me what I need.

Thank you.
