### ISSUE TITLE
Endless cycle of project assignment for repositories (project_key vs. project repos)

### ISSUE THREAD

**Issue by andreaslarfors** [jfrog/terraform-provider-artifactory#779] opened 2023-08-16 14:15 UTC
**Describe the bug**
We are using both the artifactory provider and the project provider.
We are declaring a project with a list of repositories, but we are not specifying the project_key attribute of our repositories.
When we run ``terraform apply`` the repositories are correctly assigned to the project.
On the subsequent run of ``terraform apply``, the artifactory provider explicitly wants to change the project_key attribute of the repositories from the project key to "default". 
If we apply this change, the repositories are no longer assigned to the project. 
On the subsequent run of ``terraform apply``, the project provider wants to reassign the repositories to the project.
On the subsequent run of ``terraform apply``, the artifactory provider wants to change the project_key attribute back to "default". 
And so this repeats with each run.

**Requirements for and issue**
- [X] A description of the bug
- [X] A fully functioning terraform snippet that can be copy&pasted 
- [X] Your version of artifactory - `Enterprise Plus 7.55.14 rev 75514900`
- [X] Your version of terraform
- [X] Your version of terraform provider:
```
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/jfrog/artifactory v8.0.0
+ provider registry.terraform.io/jfrog/project v1.1.16
```

Terraform snippet:
```
resource "project" "common" {
  key = "common"
  display_name = "Common"
  description  = "Project of common repositories"
  admin_privileges {
    manage_members   = true
    manage_resources = true
    index_resources  = true
  }
  max_storage_in_gibibytes   = 10
  block_deployments_on_limit = false
  email_notification         = true

  member {
    name  = "Andreas"
    roles = ["developer","project admin"]
  }

  group {
    name  = "qa-users"
    roles = ["developer"]
  }

  repos = ["pip-local", "docker-local"]
}

resource "artifactory_local_pypi_repository" "repo-pypi-local" {
    key = "pip-local"
    description = "A repository for distribution of python packages"
}

resource "artifactory_local_docker_v2_repository" "repo-docker-local" {
    key = "docker-local"
    description = "Common repository for Docker images"
}
```

Output on first ``terraform apply`` run:
```
Terraform will perform the following actions:

  # module.projects.project.common will be updated in-place
  ~ resource "project" "common" {
        id                         = "common"
      ~ repos                      = [
          + "docker-local",
          + "pip-local",
        ]
        # (6 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

```
Output on second ``terraform apply`` run:
```
Terraform will perform the following actions:

  # artifactory_local_docker_v2_repository.repo-docker-local will be updated in-place
  ~ resource "artifactory_local_docker_v2_repository" "repo-docker-local" {
        id                                    = "docker-local"
      ~ project_key                           = "common" -> "default"
        # (35 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # artifactory_local_pypi_repository.repo-pypi-local will be updated in-place
  ~ resource "artifactory_local_pypi_repository" "repo-pypi-local" {
        id                                    = "pip-local"
      ~ project_key                           = "common" -> "default"
        # (31 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

```

**Expected behavior**
Because we are not specifying the project_key of the repository objects, we expect the Artifactory provider to ignore this attribute. Alternatively, if the provider could be configured to ignore the project_key attribute that would be excellent.

**Additional context**
We have a workaround to use the ignore_changes on the project_key in the lifecycle block of each repository, but this means repeating this block in all of our repositories (100+).

**Comment by danielmkn** [comment] 2023-08-16 17:57
@andreaslarfors, this behavior is related to an unintended change in Artifactory 7.50.x a while ago: when there is no project assigned, Artifactory assigned `default` project to the repo. That behavior broke the provider and was the reason we supported both v6 and v7 of the provider at the same time. Starting at v7.0.0 we are expecting `default` project name assigned to the repo. 
One of the options would be to switch to v6.30.2, another option is to use lifecycle management. 
The problem is solved in Artifactory 7.65.0, but it will require a change on the provider side (with the version verification), which is not there yet.

**Comment by alexhung** [comment] 2023-09-07 17:09
@andreaslarfors The SaaS version is now 7.68.x but the self-hosted version is still only 7.63.x. We are waiting for the self-hosted version to advance beyond 7.65 before we apply the update to the provider.

**Comment by TJM** [comment] 2023-09-07 19:32
For what its worth, we ended up with the following workaround for this... every repo needs the following:

```terraform
  lifecycle {
    ignore_changes = [
      project_environments,
      project_key
    ]
  }
```

... then we just pass in a list of all the repos (too bad terraform doesn't have a collector) to the `resource "project" "whatever"`'s repos attribute.

**Closed** 2023-09-15 21:47 UTC
Labels: bug
