### ISSUE TITLE
xRay index won't turn on on remote repository

### ISSUE THREAD

**Issue by Jan-Pleva** [jfrog/terraform-provider-artifactory#494] opened 2022-06-28 07:33 UTC
**Describe the bug**
The script have parametr to turn on the xRay_index, but it does not happend. xRay index is still off.

https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/remote

![image](https://user-images.githubusercontent.com/71633160/176119984-ebc32654-fcaf-4af2-88e2-6c2f18a0f5cd.png)

Artifactory Version 7.31.13
xRay Version 3.41.4

**Comment by chb0github** [comment] 2022-06-28 17:56
We need a reproducible HCL to proceed on this issue - Highlighting the documentation doesn't help us find a bug. 

Please submit HCL that reproduces this issue or, unfortunately, we will need to close it

**Comment by alexhung** [comment] 2022-06-29 21:54
@bmanuel @Jan-Pleva I haven't been able to reproduce this issue. Using the following HCL, I am able to create a Docker remote repo and the "Enable Indexing In Xray" setting is 'On' in Artifactory.

```hcl
# Required for Terraform 0.13 and up (https://www.terraform.io/upgrade-guides/0-13.html)
terraform {
  required_providers {
    artifactory = {
      source  = "registry.terraform.io/jfrog/artifactory"
      version = "6.10.1"
    }
  }
}

provider "artifactory" {
  //  supply ARTIFACTORY_ACCESS_TOKEN / JFROG_ACCESS_TOKEN / ARTIFACTORY_API_KEY and ARTIFACTORY_URL / JFROG_URL as env vars
}

resource "artifactory_remote_docker_repository" "alex-remote-docker" {
  key                            = "alex-remote-docker"
  external_dependencies_enabled  = true
  external_dependencies_patterns = ["**/hub.docker.io/**", "**/bintray.jfrog.io/**"]
  enable_token_authentication    = true
  url                            = "https://hub.docker.io/"
  block_pushing_schema1          = true
  xray_index                     = true
}
```

**Comment by Jan-Pleva** [comment] 2022-06-30 07:09
I will prepare the HCL.

**Comment by chb0github** [comment] 2022-07-02 04:05
I literally just implemented a test to repro your case, and it works fine. That is: I can't reproduce your problem

```go
func TestGH494XrayIndexNotSticking(t *testing.T) {
	_, fqrn, name := test.MkNames("gh494", "artifactory_remote_docker_repository")
	hcl := util.ExecuteTemplate("TestGH494XrayIndexNotSticking",
		`resource "artifactory_remote_docker_repository" "{{ .key }}" {
			  key                          = "{{ .key }}"
			  url                          = "https://registry-1.docker.io/"
			  description                  = "Mirror of the public Dockerhub repository"
			  username                     = "username"
			  password                     = "password"
			  block_mismatching_mime_types = true
			  block_pushing_schema1        = false
			  enable_token_authentication  = true
			  repo_layout_ref              = "simple-default"
			  property_sets                = ["artifactory"]
			  xray_index                   = true
			  store_artifacts_locally      = true
			}`,
			map[string]interface{}{
				"key" : name,
			},
	)
	resource.Test(t, resource.TestCase{
		PreCheck:          func() { acctest.PreCheck(t) },
		ProviderFactories: acctest.ProviderFactories,
		CheckDestroy:      acctest.VerifyDeleted(fqrn, acctest.CheckRepo),
		Steps: []resource.TestStep{
			{
				Config: hcl,
				Check:  resource.TestCheckResourceAttr(fqrn, "xray_index", "true"),
			},
		},
	})
}
```

**Comment by chb0github** [comment] 2022-07-02 04:07
@bmanuel and @Jan-Pleva neither of you has listed your version of artifactory or terraform as the bug description requests

**Closed** 2022-07-06 16:06 UTC
Labels: bug
