### ISSUE TITLE
Please add more data sources

### ISSUE THREAD

**Issue by wzur-r3** [jfrog/terraform-provider-artifactory#31] opened 2021-02-05 15:41 UTC
Please add data sources to match existing resources.

For example there is `artifactory_local_repository` but there is no `artifactory_local_repository` data source.

Specifically I'd like to be able to create a virtual repository for existing repositories.

The obvious workaround for me is to run a REST API to fetch list of repositories already in Arifactory, store output in a JSON file,  subsequently read that JSON file in Terraform, and use the list of repositories in an `artifactory_local_repository` but that creates unnecessary steps.

**Comment by peters95** [comment] 2021-02-05 17:17
Hi @wzur-r3 given this is open source feel free to submit a PR with your requested changes. We will review and if it passes all our tests we will merge your PR to be included. This is a feature request vs an issue w/ the existing implementation.

**Comment by chb0github** [comment] 2021-02-17 17:19
So, give me some sample DSL you think would be appropriate. Because, I am not fully understanding you.

**Comment by chb0github** [comment] 2021-02-23 18:26
Closing ticket for lack of comment. Please feel free to open if you can give me something copy-and-paste reproducible

**Closed by chb0github** 2021-02-23 18:26 UTC
